# Generated by Django 4.2.16 on 2024-10-01 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0002_residente'),
    ]

    operations = [
        migrations.CreateModel(
            name='responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20)),
                ('celular', models.CharField(max_length=20)),
                ('telefone_comercial', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Responsavel',
                'verbose_name_plural': 'Responsaveis',
            },
        ),
    ]
