# Generated by Django 4.2.16 on 2024-10-02 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0004_categoria_endereco_inscricao_remove_residente_cpf_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endereco',
            options={'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereços'},
        ),
        migrations.AlterModelOptions(
            name='inscricao',
            options={'verbose_name': 'Incrição', 'verbose_name_plural': 'Incrições'},
        ),
        migrations.AlterModelOptions(
            name='responsavel',
            options={'verbose_name': 'Responsável', 'verbose_name_plural': 'Responsáveis'},
        ),
    ]
