# Generated by Django 4.2.16 on 2024-10-06 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0007_alter_residente_options_residente_cpf_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscricao',
            options={'verbose_name': 'Inscrição', 'verbose_name_plural': 'Inscrições'},
        ),
        migrations.AddField(
            model_name='inscricao',
            name='Residente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='aplic.residente'),
            preserve_default=False,
        ),
    ]
